src/IT/ResourceBundle/Entity/Dispositif.php
<?php
/**
 * Created by IntelliJ IDEA.
 * User: TyreX
 * Date: 23/02/2018
 * Time: 10:19
 */

namespace IT\ResourceBundle\Entity;

use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use JMS\Serializer\Annotation as Serializer;
use JMS\Serializer\Annotation\ExclusionPolicy;
use JMS\Serializer\Annotation\Expose;
use IT\ResourceBundle\Entity\Image;
use Swagger\Annotations as SWG;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="IT\ResourceBundle\Repository\DispositifsRepository")
 * @SWG\Definition(type="object", @SWG\Xml(name="Dispositif"))
 */
class Dispositif extends Ressource
{

    /**
     * @var string
     * @ORM\Column(name="model", type="string", length=50)
     * @Serializer\Groups({"categories","resources"})
     * @Assert\NotBlank()
     * @Assert\Length(
     *      min = 5,
     *      max = 50,
     *      minMessage = "Your model must be at least {{ limit }} characters long",
     *      maxMessage = "Your model cannot be longer than {{ limit }} characters"
     * )
     * @SWG\Property(property="model",type="string",description="The model of the device.")
     */
    private $model;


    /**
     * @var string
     *
     * @ORM\Column(name="os", type="string", length=20)
     * @Serializer\Groups({"categories","resources"})
     * @Assert\NotBlank()
     * @Assert\Choice(
     *     choices={"ANDROID", "IOS","WINDOWS","LINUX"},
     *      message="Choose a valid OS."
     * )
     * @SWG\Property(type="string",description="Systéme d'exploitation du dispositif.")
     */
    private $os;

    /**
     * @var string
     * @ORM\Column(name="OsVersion", type="string")
     * @Serializer\Groups({"categories","resources"})
     * @Assert\NotBlank()
     * @Assert\Regex("/(^.+)\.(\w+)/",
     *     message="This is not a valid version")
     * @SWG\Property(type="string",description="Version of the system's OS")
     */
    private $OsVersion;

    /**
     * @var string
     *
     * @ORM\Column(name="device_UUID", type="string", length=80)
     * @Serializer\Groups({"categories","resources"})
     * @SWG\Property(type="string",description="Identifiant unique du dispositif.")
     */
    private $deviceUUID;

    /**
     * @var string
     *
     * @ORM\Column(name="cpu", type="string", length=40)
     * @Serializer\Groups({"categories","resources"})
     * @Assert\NotBlank()
     * @SWG\Property(type="string",description="Cpu of the device.")
     */
    private $cpu;

    /**
     * @var int
     *
     * @ORM\Column(name="cpu_cores", type="integer")
     * @Serializer\Groups({"categories","resources"})
     * @SWG\Property(type="number",description="Nombre de coeurs du dispositif.")
     */
    private $cpuCores;

    /**
     * @var float
     *
     * @ORM\Column(name="ram", type="float")
     * @Serializer\Groups({"categories","resources"})
     * @Assert\NotBlank()
     * @Assert\Range(
     *      min = 0.512,
     *      max = 24.000,
     *      minMessage = "Your RAM must be at least {{ limit }} MB",
     *      maxMessage = "Your RAM be greater than {{ limit }} MB"
     * )
     * @SWG\Property(type="number",description="Ram du dispositif.")
     */
    private $ram;

    /**
     * @var string
     *
     * @ORM\Column(name="disk_space", type="string")
     * @Serializer\Groups({"categories","resources"})
     * @SWG\Property(description="Storage du dispositif.")
     */
    private $diskSpace;

    /**
     * @var string
     *
     * @ORM\Column(name="free_disk_space", type="string")
     * @Serializer\Groups({"categories","resources"})
     * @SWG\Property(description="Storage disponible du dispositif.")
     */
    private $freeDiskSpace;

    /**
     * @var string
     *
     * @ORM\Column(name="device_token", type="string",nullable=true)
     * @Serializer\Groups({"categories","resources"})
     * @SWG\Property(description="Token du device pour le push notification.")
     */
    private $device_token;

    /**
     * @var string
     *
     * @ORM\Column(name="used_disk_space", type="string" ,nullable=true)
     * @Serializer\Groups({"categories","resources"})
     * @SWG\Property(description="Storage utilisé du dispositif.")
     */
    private $usedDiskSpace;


    /**
     * @var string
     * @ORM\Column(name="resolution", type="string" ,length=20)
     * @Serializer\Groups({"categories","resources"})
     * @Assert\NotBlank()
     * @Assert\Regex("/(^[0-9]{3,4}+)(x|X)([0-9]{3,4}$)/",
     *     message="This is not a valid resolution")
     * @SWG\Property(type="string",description="Resolution of the device.")
     */
    private $resolution;

    /**
     * @ORM\OneToMany(targetEntity="IT\ResourceBundle\Entity\Application", mappedBy="dispositif" ,cascade={"remove", "persist"},orphanRemoval=true)
     * @Serializer\Groups({"categories","resources"})
     **/
    private $apps;


    /**
     * @ORM\OneToMany(targetEntity="Image", mappedBy="dispositif" ,cascade={"remove", "persist"},orphanRemoval=true)
     **/
    private $images;


    public function __construct()
    {
        parent::__construct();
        $this->reservation = new ArrayCollection();
        $this->apps = new ArrayCollection();
        $this->images = new ArrayCollection();
    }


    /**
     * add image
     *
     * @param Image $image
     * @return Dispositif
     */
    public function addImage($image)
    {

        $image->setDispositif($this);
        $this->images[] = $image;
        return $this;
    }

    /**
     * Set images
     *
     * @param string $images
     * @return Dispositif
     */
    public function setImages($images)
    {
        $this->images = $images;

        return $this;
    }

    /**
     * Get $images
     *
     * @return collection
     */
    public function getImages()
    {
        return $this->images;
    }

    public function removeImage($image)
    {
        $this->images->removeElement($image);
    }

    /**
     * @return mixed
     */
    public function getApps()
    {
        return $this->apps;
    }

    /**
     * @param mixed array $apps
     */
    public function setApps($apps)
    {
        $this->apps = $apps;
    }

    /**
     * {@inheritdoc}
     */
    public function addApp($app)
    {
        $app = strtoupper($app);
        if (!in_array($app, $this->apps, true)) {
            $this->apps[] = $app;
        }
        return $this;
    }

    /**
     * @return string
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * @param string $model
     */
    public function setModel(string $model)
    {
        $this->model = $model;
    }


    /**
     * @return string
     */
    public function getOs()
    {
        return $this->os;
    }

    /**
     * @param string $os
     */
    public function setOs(string $os)
    {
        $this->os = $os;
    }

    /**
     * @return string
     */
    public function getOsVersion()
    {
        return $this->OsVersion;
    }

    /**
     * @param string $OsVersion
     */
    public function setOsVersion(string $OsVersion)
    {
        $this->OsVersion = $OsVersion;
    }

    /**
     * @return string
     */
    public function getDeviceUUID()
    {
        return $this->deviceUUID;
    }

    /**
     * @param string $deviceUUID
     */
    public function setDeviceUUID(string $deviceUUID)
    {
        $this->deviceUUID = $deviceUUID;
    }

    /**
     * @return string
     */
    public function getCpu()
    {
        return $this->cpu;
    }

    /**
     * @return string
     */
    public function getDeviceToken()
    {
        return $this->device_token;
    }

    /**
     * @param string $device_token
     */
    public function setDeviceToken(string $device_token)
    {
        $this->device_token = $device_token;
    }


    /**
     * @param string $cpu
     */
    public function setCpu(string $cpu)
    {
        $this->cpu = $cpu;
    }

    /**
     * @return int
     */
    public function getCpuCores()
    {
        return $this->cpuCores;
    }

    /**
     * @param int $cpuCores
     */
    public function setCpuCores(int $cpuCores)
    {
        $this->cpuCores = $cpuCores;
    }

    /**
     * @return float
     */
    public function getRam()
    {
        return $this->ram;
    }

    /**
     * @param float $ram
     */
    public function setRam(float $ram)
    {
        $this->ram = $ram;
    }

    /**
     * @return string
     */
    public function getDiskSpace()
    {
        return $this->diskSpace;
    }

    /**
     * @param string $diskSpace
     */
    public function setDiskSpace(string $diskSpace)
    {
        $this->diskSpace = $diskSpace;
    }

    /**
     * @return string
     */
    public function getFreeDiskSpace()
    {
        return $this->freeDiskSpace;
    }

    /**
     * @param string $freeDiskSpace
     */
    public function setFreeDiskSpace(string $freeDiskSpace)
    {
        $this->freeDiskSpace = $freeDiskSpace;
    }

    /**
     * @return string
     */
    public function getUsedDiskSpace()
    {
        return $this->usedDiskSpace;
    }

    /**
     * @param string $usedDiskSpace
     */
    public function setUsedDiskSpace(string $usedDiskSpace)
    {
        $this->usedDiskSpace = $usedDiskSpace;
    }

    /**
     * @return string
     */
    public function getResolution()
    {
        return $this->resolution;
    }

    /**
     * @param string $resolution
     */
    public function setResolution(string $resolution)
    {
        $this->resolution = $resolution;
    }


    public function __toString()
    {
        return $this->model;
    }


}

src/IT/ResourceBundle/Controller/DispositifController.php
<?php

namespace IT\ResourceBundle\Controller;

use IT\ResourceBundle\Entity\Dispositif;
use FOS\RestBundle\Controller\Annotations as Rest;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;

/**
 * Class DispositifController
 * @package IT\ResourceBundle\Controller
 */
class DispositifController extends Controller
{
    /**
     * @Route("/add" , name="add_device")
     * @Template()
     * @param Request $request
     * @return array
     */
    public function add_deviceAction(Request $request)
    {
        $message = null;
        $dispositif = new Dispositif();

        $form = $this->createForm("IT\ResourceBundle\Form\DispositifType", $dispositif);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            foreach ($dispositif->getImages() as $image) {
                $dispositif->addImage($image);
            }
            foreach ($dispositif->getApps() as $app){
                $app->setDispositif($dispositif);
            }

            $em->persist($dispositif);
            $em->flush();
            $message = "Dispositif a été crée avec succée";
        }

        return array('dispositifForm' => $form->createView(), 'message' => $message);
    }


    /**
     * @Route("/edit/{id}",name="edit_device")
     * @Template()
     * @param $id
     * @return array
     */
    public function edit_deviceAction($id)
    {
        $message = null;
        $em = $this->getDoctrine()->getManager();
        $dispositif = $em->getRepository('ITResourceBundle:Dispositif')->find($id);
        $form = $this->createForm('IT\ResourceBundle\Form\DispositifType', $dispositif);
        $request = $this->get('request_stack')->getCurrentRequest();
        $form->handleRequest($request);

        if ($form->isValid()) {
            foreach ($dispositif->getApps() as $app){
                $app->setDispositif($dispositif);
            }

//            foreach ($dispositif->getImages() as $image) {
//                $dispositif->addImage($image);
//            }

            $em->persist($dispositif);
            $em->flush();
            $message = "Le dispositif a étè bien modifié";

        }

        return array('dispositifForm' => $form->createView(), 'message' => $message);
    }


    /**
     * @Route("/list" , name="list_devices")
     * @Template()
     * @param Request $request
     * @return array
     */
    public function list_devicesAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $dispositifs = $em->getRepository("ITResourceBundle:Dispositif")->findAll();
        $paginator  = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $dispositifs,
            $request->query->get('page', 1)/*page number*/,
            5/*limit per page*/
        );
        return array('dispositifs' => $pagination);
    }



    /**
     * @Route("/geolocate/{id}" , name="geolocate_device")
     * @Template()
     */
    public function geolocate_deviceAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $dispositif = $em->getRepository('ITResourceBundle:Dispositif')->findOneBy(['id' => $id]);
        return array('dispositif' => $dispositif);
    }




}

src/IT/ResourceBundle/Resources/views/Dispositif/formThemeWithButtons.html.twig
{% block Application_widget %}
        <div class="row">
            <div class="col-md-6">
                {{ form_widget(form) }}
            </div>
            <div class="col-md-2">
                {# Note that "city" on classes below are the same as on "prefix" option #}
                <a href="#" class="Application-remove btn btn-default" title="Delete Application"><span
                            class="glyphicon glyphicon-trash"></span></a>
                <a href="#" class="Application-add btn btn-default" title="Add Application"><span
                            class="glyphicon glyphicon-plus-sign"></span></a>
            </div>
            <div class="col-md-3">
                <a href="#" class="Application-up btn btn-default" title="Move Application up"><span class="glyphicon glyphicon-arrow-up"></span></a>
                <a href="#" class="Application-down btn btn-default" title="Move Application down"><span class="glyphicon glyphicon-arrow-down"></span></a>
            </div>
            <div class="col-md-1">
                <a href="#" class="Application-duplicate btn btn-default" title="Duplicate Application"><span class="glyphicon glyphicon-th-large"></span></a>
            </div>
        </div>


{% endblock %}

{% block Image_widget %}

    <div class="row">
        <div class="col-md-6">
            {{ form_widget(form) }}
        </div>
        <div class="col-md-2">
            {# Note that "hobby" on classes below are the same as on "prefix" option #}
            <a href="#" class="Image-remove btn btn-default" title="Delete hobby"><span
                        class="glyphicon glyphicon-trash"></span></a>
            <a href="#" class="Image-add btn btn-default" title="Add hobby"><span
                        class="glyphicon glyphicon-plus-sign"></span></a>
        </div>
        <div class="col-md-3">
            <a href="#" class="Image-up btn btn-default" title="Move Image up"><span class="glyphicon glyphicon-arrow-up"></span></a>
            <a href="#" class="Image-down btn btn-default" title="Move Image down"><span class="glyphicon glyphicon-arrow-down"></span></a>
        </div>
        <div class="col-md-1">
            <a href="#" class="Image-duplicate btn btn-default" title="Duplicate Image"><span class="glyphicon glyphicon-th-large"></span></a>
        </div>
    </div>

{% endblock %}

src/IT/ResourceBundle/Resources/views/Dispositif/form_ressource.html.twig
<h3>{{ category }}</h3>
{% form_theme form 'bootstrap_3_layout.html.twig' %}
{{ form_start(form, {'attr' : {'id':'formID','class':'form-bordered'} }) }}
{{ form_end(form) }}

src/IT/ResourceBundle/Resources/views/Dispositif/geolocate_device.html.twig
{% extends '::base.html.twig' %}
{% block title %}

{% endblock %}
{% block stylesheets %}
    {% stylesheets
        'bundles/itreservation/app/plugins/bower_components/vect-map/jqvmap.min.css'
        filter='cssrewrite' %}
        <link rel="stylesheet" href="{{ asset_url }}" />
    {% endstylesheets %}
{% endblock %}

{% block gestion_dispositifs %}
    <a href="#" class="waves-effect active"><i class="icon-screen-smartphone fa-fw" data-icon="v"></i>
        <span class="hide-menu"> Gestion Ressources <span class="fa arrow"></span></span></a>
{% endblock %}

{% block content %}
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row bg-title">
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <h4 class="page-title">Vector Page</h4></div>
                <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                    <ol class="breadcrumb">
                        <li><a href="#">Dashboard</a></li>
                        <li class="active">Vector Page</li>
                    </ol>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- row -->
            <div class="row">
                <div class="col-sm-12 col-xs-12">
                    <div class="white-box">
                        <h3 class="box-title">Proym IT</h3>
                        <div id="proxym" style="height: 450px"></div>

                    </div>
                </div>
            </div>
            <!-- /.row -->
            <!-- row -->
            <div class="row">
                <div class="col-sm-12 col-xs-12">
                    <div class="white-box">
                        <h3 class="box-title">Tunisia</h3>
                        <div id="vmap" style="width: 600px; height: 400px;"></div>

                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
        <footer class="footer text-center"> 2017 &copy; Gestion de réservation des ressources</footer>
    </div>
{% endblock %}

{% block scripts %}
    {% javascripts
        '@ITReservationBundle/Resources/public/app/plugins/bower_components/vect-map/jquery.vmap.min.js'
        '@ITReservationBundle/Resources/public/app/plugins/bower_components/vect-map/maps/jquery.vmap.tunisia.js'
        '@ITReservationBundle/Resources/public/app/plugins/bower_components/vect-map/maps/jquery.vmap.proxym.js'
    %}
        <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
    <script>
        jQuery('#vmap').vectorMap({
            map: 'tunisia',
            backgroundColor: null,
            color: '#bdaa36',
            hoverOpacity: 0.7,
            selectedColor: '#355876',
            enableZoom: true,
            showTooltip: true,
//            values: sample_data,
            scaleColors: ['#C8EEFF', '#006491'],
            normalizeFunction: 'polynomial',
            multiSelectRegion:false,
            onRegionClick: function(element, code, region)
            {
                var message = 'You clicked "'
                    + region
                    + '" which has the code: '
                    + code.toUpperCase();

                alert(message);
            }
        });

        jQuery('#proxym').vectorMap({
            map: 'proxym',
            backgroundColor: null,
            color: '#bdaa36',
            hoverOpacity: 0.7,
            selectedColor: '#355876',
            enableZoom: true,
            showTooltip: true,
//            values: sample_data,
            scaleColors: ['#C8EEFF', '#006491'],
            normalizeFunction: 'polynomial',
            multiSelectRegion:false,
            onRegionClick: function(element, code, region)
            {
                var message = 'You clicked "'
                    + region
                    + '" which has the code: '
                    + code.toUpperCase();

                alert(message);
            }
        });
    </script>
    {#<script src="{{ asset('bundles/app/assets/js/jvectormap.custom.js') }}"></script>#}
{% endblock %}

src/IT/ResourceBundle/Resources/views/Dispositif/list_devices.html.twig
{% extends '::base.html.twig' %}
{% block title %}
    Liste des dispositifs
{% endblock %}

{% block stylesheets %}
    {% stylesheets
        'bundles/itreservation/app/plugins/bower_components/footable/css/footable.core.css'
        'bundles/itreservation/app/plugins/bower_components/Magnific-Popup-master/dist/magnific-popup.css'
        filter='cssrewrite' %}
        <link rel="stylesheet" href="{{ asset_url }}"/>
    {% endstylesheets %}
{% endblock %}

{% block gestion_dispositifs %}
    <a href="#" class="waves-effect active"><i class="icon-screen-smartphone fa-fw" data-icon="v"></i>
        <span class="hide-menu"> Gestion Ressources <span class="fa arrow"></span></span></a>
{% endblock %}

{% block content %}
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row bg-title">
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <h4 class="page-title">Ressources</h4></div>
                <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                    <ol class="breadcrumb">
                        <li><a href="#">Accueil</a></li>
                        <li><a href="#">Dispositifs</a></li>
                        <li class="active">Liste des dispositifs</li>
                    </ol>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- .row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="white-box">
                        <h3 class="box-title m-b-0">Liste des Dispositifs</h3>
                        {#<label class="form-inline">Afficher#}
                            {#<select id="demo-show-entries" class="form-control input-sm">#}
                                {#<option value="10">10</option>#}
                                {#<option value="15">15</option>#}
                                {#<option value="20">20</option>#}
                            {#</select> entrés </label>#}
                        <div class="btn-group">
                            <a href="{{ path('add_device') }}" class="right">
                                <button id="sample_editable_1_new" class="btn btn-default"> Ajouter dispositif
                                    <i class="fa fa-plus"></i>
                                </button>
                            </a>
                        </div>
                        <hr>
                        <table id="demo-foo-pagination" class="table color-table info-table m-b-0 toggle-arrow-tiny"
                               data-page-size="10">
                            <thead>
                            <tr>
                                <th data-toggle="true"> Modéle</th>
                                <th data-hide="phone"> OS</th>
                                <th data-hide="phone"> Version OS</th>
                                <th data-hide="phone"> Processeur</th>
                                <th data-hide="phone"> Ram</th>
                                <th data-hide="phone"> Résolution</th>
                                <th data-hide="phone"> Statut</th>
                                <th data-hide="phone"> Localiser</th>
                                <th data-hide="phone">Verrouiller</th>
                                <th>Action</th>
                                <th data-hide="all"> Applications</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for dispositif in dispositifs %}
                                <tr>
                                    <td>
                                        <a href="{{ path('edit_device',{'id':dispositif.id}) }}">{{ dispositif.model }}</a>
                                    </td>
                                    <td>{{ dispositif.os }}</td>
                                    <td>{{ dispositif.osVersion }}</td>
                                    <td>{{ dispositif.cpu }}</td>
                                    <td>{{ dispositif.ram }} GB</td>
                                    <td>{{ dispositif.resolution }}</td>
                                    <td>
                                        {% if dispositif.status == 1 %}
                                            <span class="label label-table label-success">Fonctionnel</span>
                                        {% elseif dispositif.status == 0 %}
                                            <span class="label label-table label-danger">Détruit</span>
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if dispositif.status == 1 %}
                                            <a href="{{ path('geolocate_device',{'id':dispositif.id}) }}">
                                                <button class="btn btn-block btn-outline btn-primary">Localiser</button>
                                            </a>
                                        {% else %}
                                            <a href="#">
                                                <button class="btn btn-block btn-outline btn-primary" disabled>
                                                    Localiser
                                                </button>
                                            </a>
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if dispositif.status == 1 %}
                                            <a href="{{ path('geolocate_device',{'id':dispositif.id}) }}">
                                                <button class="btn btn-block btn-outline btn-danger">Verrouiller
                                                </button>
                                            </a>
                                        {% else %}
                                            <a href="#">
                                                <button class="btn btn-block btn-outline btn-danger" disabled>
                                                    Verrouiller
                                                </button>
                                            </a>
                                        {% endif %}
                                    </td>

                                    <td>
                                        <a href="{{ path('edit_device',{'id':dispositif.id}) }}">
                                            <button class="btn btn-block btn-outline btn-secondary">
                                                Modifier
                                            </button>
                                        </a>
                                    </td>
                                    <td>
                                        <ul class="row el-element-overlay m-b-40">
                                            {% for app in dispositif.apps %}
                                                <li class="col-md-12 col-sm-12 col-xs-12">
                                                    {{ app.name }}
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </td>

                                </tr>
                            {% endfor %}
                            </tbody>
                            <tfoot>
                            <tr>
                                <td colspan="5" class="hidden">
                                    <div class="text-right">
                                        <ul class="pagination pagination-split m-t-30"></ul>
                                    </div>
                                </td>
                            </tr>
                            </tfoot>
                        </table>
                        <div class="navigation row">
                            <div class="center-block">
                                {{ knp_pagination_render(dispositifs) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
        <footer class="footer text-center"> 2017 &copy; Gestion de réservation des ressources</footer>
    </div>
{% endblock %}

{% block scripts %}
    {% javascripts
        '@ITReservationBundle/Resources/public/app/plugins/bower_components/footable/js/footable.all.min.js'
        '@ITReservationBundle/Resources/public/app/assets/js/footable-init.js'

        '@ITReservationBundle/Resources/public/app/plugins/bower_components/Magnific-Popup-master/dist/jquery.magnific-popup.min.js'
        '@ITReservationBundle/Resources/public/app/plugins/bower_components/Magnific-Popup-master/dist/jquery.magnific-popup-init.js' %}
        <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
    <!--FooTable init-->
    <!-- Custom Theme JavaScript -->
    <script>
        $("#notifier").click(function () {
            $('.LoadingRoot').show();
            $.ajax({
                type: 'POST',
                url: "http://localhost:8080/message",
                //TODO parse time
                data: 'message=' + " Hi everyone",
                dataType: 'json',
                success: function (data) {
                    $('.LoadingRoot').hide();
                }
            });
        });

    </script>
{% endblock %}